# Conexão com o Oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=RM565146
spring.datasource.password=170806
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configurações do JPA/Hibernate
# Atualiza as tabelas automaticamente de acordo com as suas classes
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Mostra o SQL gerado no console (ótimo para debugar e aprender)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
